### ISSUE TITLE
Can it be applied to newer thinkpads?

### ISSUE THREAD

**Issue by amosbird** [peterberbec/KeyboardTrackpointTouchPad#1]
Hello! This project is promising. I wonder if it can be adjusted to newer version of thinkpads such as thinkpad x1 extreme.

**Comment by peterberbec** [comment]
I'm not sure.

I've looked at the connectors on the X240 (I have one of those too) and they are TINY. This one is just at the limits of what I was able to hand-solder, but any smaller and you'd basically need to design a PCB to connect to the ribbon cable.

**Comment by peterberbec** [comment]
Here's the first concept: https://www.youtube.com/watch?v=Sr2X2P3-wsA Look at the mess at of green wires.

Here's it refined: https://www.youtube.com/watch?v=O9toxFcVfDY I had a buddy make a PCB
